"""Init

Revision ID: b821e47a4592
Revises: 
Create Date: 2025-11-12 23:19:26.570395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b821e47a4592'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_buildings_geog', 'buildings', ['geog'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_buildings_address'), 'buildings', ['address'], unique=True)
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uix_name_parent_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_scope',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'scope_id')
    )
    op.create_index(op.f('ix_organization_scope_organization_id'), 'organization_scope', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_scope_scope_id'), 'organization_scope', ['scope_id'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_id'), 'phones', ['id'], unique=False)
    op.create_index(op.f('ix_phones_phone_number'), 'phones', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_phone_number'), table_name='phones')
    op.drop_index(op.f('ix_phones_id'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_organization_scope_scope_id'), table_name='organization_scope')
    op.drop_index(op.f('ix_organization_scope_organization_id'), table_name='organization_scope')
    op.drop_table('organization_scope')
    op.drop_table('organizations')
    op.drop_table('scopes')
    op.drop_index(op.f('ix_buildings_address'), table_name='buildings')
    op.drop_index('idx_buildings_geog', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    # ### end Alembic commands ###
